[common]
# All properties defined in this section will be merged into each actor group's section.
# The primary purpose is to define default values of system settings (logging, dumping, and so on).

# Parameters and their defaults
# Mailbox
#system.mailbox.capacity = 100
#
# Logging
#system.logging.max_level = "Info" # one of: Trace, Debug, Info, Warn, Error, Off.
#system.logging.max_rate_per_level = 1_000    # per second
#
# Dumping
#system.dumping.max_level = "Off" # one of: Normal, Verbose, Total, Off.
#system.dumping.max_rate_per_class = 10_000 # per second
#
# Telemetry
#system.telemetry.per_actor_group = true
#system.telemetry.per_actor_key = false

# Each parameter can be redefined on the actor group level.

[system.loggers]
#sink = "File"  # "Stdout" by default
#path = "example.log"
#format.with_location = false
#format.with_module = false
#max_line_size = "1KiB"
#
# It's possible to set `max_level` for a specific target:
#targets.hyper.max_level = "Trace"
#targets."hyper::server".max_level = "Warn"
# Regardless of what's configured here, any `Debug` or `Trace` logs
# from outside the actor system would be filtered out.

[system.telemeters]
sink = "OpenMetrics"
listen = "0.0.0.0:9042"
#global_labels = [["label", "value"]]
#quantiles = [0.75, 0.9, 0.95, 0.99]

[system.dumpers]
path = "example.{class}.dump"

[producers]
group_count = 3
item_count = 10
# Override restart policy for this actor group.
[producers.system.restart_policy]
when = "OnFailure"
min_backoff = "5s"
max_backoff = "30s"

[aggregators]
system.telemetry.per_actor_key = true
#system.telemetry.per_actor_key = ["(.*)", "${1}-overrided"]
# Override restart policy for this actor group.
[aggregators.system.restart_policy]
when = "OnFailure"
min_backoff = "5s"
max_backoff = "30s"

[reporters]
interval = "2s"
