[system.telemeters]
sink = "Prometheus"
address = "0.0.0.0:9042"

[system.dumpers]
path = "example.backend.{class}.dump"

[system.network]
listener.tcp = "127.0.0.1:3043"
discovery.predefined = [
    "127.0.0.1:3042"
]
