[system.telemeters]
sink = "Prometheus"
address = "0.0.0.0:9101"

[system.dumpers]
path = "example.bob.{class}.dump"

[system.network]
listen = ["tcp://127.0.0.1:9201"]
discovery.predefined = ["tcp://127.0.0.1:9200"]
